from threading import Lock

mutex = Lock()

AUTOSAVE_INTERVAL_SECONDS = 5 * 60

MONGODB_DATABASE_NAME = "server"

MONGODB_IDS_COLLECTION = "identifiers"
MONGODB_IDS_COLLECTION_TYPE_FIELD = "type"
MONGODB_IDS_COLLECTION_LAST_ID_FIELD = "last-id"

MONGODB_UUID_LOOKUP_COLLECTION = "name-to-uuid"
MONGODB_UUID_LOOKUP_COLLECTION_NAME_FIELD = "name"
MONGODB_UUID_LOOKUP_COLLECTION_UUID_FIELD = "uuid"

REDIS_UUID_LOOKUP_HSET = "name-to-uuid"
REDIS_PUNISHMENTS_LAST_ID_KEY = "last-ids:punishments"

REDIS_UUID_LOOKUP_CHANNEL = "name-to-uuid"
REDIS_UUID_LOOKUP_RESPONSE_CHANNEL = "response_name-to-uuid"
REDIS_PUNISHMENT_CHANNEL = "punishment"
REDIS_SERVER_HEARTBEAT_CHANNEL = "server-heartbeat"

channels = [
	REDIS_UUID_LOOKUP_CHANNEL,
	REDIS_PUNISHMENT_CHANNEL,
	REDIS_SERVER_HEARTBEAT_CHANNEL
]