#!/bin/sh

if [ ! -f "${CONTAINER_PROXY_FILES_PATH}/${BUNGEECORD_JAR}" ]; then
	wget ${BUNGEECORD_LINK} -P ${CONTAINER_PROXY_FILES_PATH}
fi

cd ${CONTAINER_PROXY_FILES_PATH}

java -Xms${SERVER_INITIAL_RAM} -Xmx${SERVER_MAX_RAM} -jar ${BUNGEECORD_JAR}